/**
 * Data loading and caching for Entra ID roles.
 * Handles fetching role definitions from the server with in-memory caching.
 */

import { EntraIDRole } from '@/types/rbac';
import { CACHE_TTL_MS } from '@/config/constants';

/**
 * In-memory cache for Entra ID role data.
 * Reduces fetch calls and improves UI responsiveness.
 * Cache expires after 6 hours.
 */
let entraIdRolesCache: EntraIDRole[] | null = null;
let entraIdRolesCacheExpiry = 0;
let entraIdActionsMapCache: Map<string, { name: string; roleCount: number }> | null = null;
let entraIdActionsMapCacheExpiry = 0;

type EntraIdRolesDataStatus = 'unknown' | 'missing' | 'available';
let entraIdRolesDataStatus: EntraIdRolesDataStatus = 'unknown';

export function getEntraIDRolesDataStatus(): EntraIdRolesDataStatus {
  return entraIdRolesDataStatus;
}

/**
 * Loads Entra ID role definitions with extended metadata.
 * Data includes role names, permissions, and privilege scores.
 * Generated by scripts/updateRbacData.ts and cached for 6 hours.
 */
export async function loadEntraIDRoles(): Promise<EntraIDRole[]> {
  const now = Date.now();

  if (entraIdRolesCache && entraIdRolesCacheExpiry > now) {
    return entraIdRolesCache;
  }

  try {
    const response = await fetch('/data/entraid-roles.json');
    if (!response.ok) {
      if (response.status === 404) {
        // File doesn't exist yet - user needs to run npm run fetch-entraid-roles
        console.warn('Entra ID roles data not found. Run: npm run fetch-entraid-roles');
        entraIdRolesDataStatus = 'missing';
        return [];
      }
      throw new Error(`Failed to load Entra ID roles: ${response.statusText}`);
    }

    const roles = await response.json() as EntraIDRole[];
    entraIdRolesCache = roles;
    entraIdRolesCacheExpiry = now + CACHE_TTL_MS;
    entraIdRolesDataStatus = 'available';

    return roles;
  } catch (error) {
    if (error instanceof Error && error.message.includes('404')) {
      entraIdRolesDataStatus = 'missing';
      return [];
    }
    throw new Error(`Failed to load Entra ID roles: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Extracts unique service namespaces from all Entra ID roles.
 * Returns namespaces like "microsoft.directory", "microsoft.azure", etc.
 */
export async function getEntraIDNamespaces(): Promise<string[]> {
  const roles = await loadEntraIDRoles();
  const namespaceSet = new Set<string>();

  for (const role of roles) {
    for (const permission of role.rolePermissions) {
      for (const action of permission.allowedResourceActions) {
        const namespace = action.split('/')[0];
        if (namespace && namespace !== '*') {
          namespaceSet.add(namespace);
        }
      }
    }
  }

  return Array.from(namespaceSet).sort();
}

/**
 * Extracts all unique actions from Entra ID roles.
 * Returns a map of action name to role count (how many roles grant this action).
 */
export async function extractActionsFromEntraIDRoles(): Promise<Map<string, { name: string; roleCount: number }>> {
  const now = Date.now();

  // Return cached data if available and fresh
  if (entraIdActionsMapCache && entraIdActionsMapCacheExpiry > now) {
    return entraIdActionsMapCache;
  }

  const roles = await loadEntraIDRoles();
  const actionsMap = new Map<string, { name: string; roleCount: number }>();

  for (const role of roles) {
    if (!role.isEnabled) continue;

    for (const permission of role.rolePermissions) {
      for (const action of permission.allowedResourceActions) {
        // Include all actions, including wildcards (e.g., allEntities/allTasks)
        // Many Entra ID services only have wildcard-style permissions
        const key = action.toLowerCase();
        const existing = actionsMap.get(key);

        if (existing) {
          existing.roleCount++;
        } else {
          actionsMap.set(key, {
            name: action,
            roleCount: 1
          });
        }
      }
    }
  }

  entraIdActionsMapCache = actionsMap;
  entraIdActionsMapCacheExpiry = now + CACHE_TTL_MS;

  return actionsMap;
}

/**
 * Gets all actions for a specific Entra ID namespace.
 * Example: "microsoft.directory" returns all directory actions
 */
export async function getEntraIDActionsByNamespace(namespace: string): Promise<string[]> {
  const actionsMap = await extractActionsFromEntraIDRoles();
  const results: string[] = [];
  const namespaceLower = namespace.toLowerCase();

  for (const [key, actionData] of Array.from(actionsMap.entries())) {
    if (key.startsWith(namespaceLower + '/')) {
      results.push(actionData.name);
    }
  }

  return results.sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));
}

/**
 * Searches Entra ID actions by query string.
 * Returns actions matching the query in name or namespace.
 */
export async function searchEntraIDActions(query: string): Promise<string[]> {
  if (query.length < 2) {
    return [];
  }

  const actionsMap = await extractActionsFromEntraIDRoles();
  const results: string[] = [];
  const queryLower = query.toLowerCase();

  for (const [, actionData] of Array.from(actionsMap.entries())) {
    if (actionData.name.toLowerCase().includes(queryLower)) {
      results.push(actionData.name);
    }
  }

  return results
    .sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))
    .slice(0, 100); // Limit to 100 results
}

/**
 * Pre-loads and caches the Entra ID actions map in the background.
 */
export async function preloadEntraIDActionsCache(): Promise<void> {
  try {
    await extractActionsFromEntraIDRoles();
  } catch (error) {
    console.warn('Failed to preload Entra ID actions cache:', error);
  }
}
